---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- apps/application-cert-manager.yaml
- apps/application-cert-manager-config.yaml
- apps/application-traefik.yaml
#- apps/application-argocd.yaml
- apps/application-nginx.yaml
