---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
#- apps/application-argocd.yaml
- apps/application-cert-manager.yaml
- apps/application-cert-manager-config.yaml
- apps/application-cloudflared.yaml
- apps/application-jackett.yaml
- apps/application-jellyfin.yaml
#- apps/application-nginx.yaml
- apps/application-traefik.yaml
- apps/application-transmission.yaml