apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager-config
  namespace: argocd
spec:
  dependsOn:
    - name: cert-manager
  project: default
  source:
    repoURL: https://github.com/SmoofOperator/homelab-deployments.git
    path: cert-manager-config
    targetRevision: main
  destination:
    server: https://kubernetes.default.svc
    namespace: cert-manager
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
