apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: seerr
  namespace: media
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`seerr.teklogi.systems`)
      kind: Rule
      services:
        - name: seerr
          port: 5055
    - match: Host(`overseerr.teklogi.systems`)
      kind: Rule
      services:
        - name: seerr
          port: 5055
